# base image
FROM node:10.11.0-alpine

# set working directory
RUN mkdir /usr/src
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json package-lock.json /usr/src/app/
RUN npm i -g --silent react-scripts@2.0.3
RUN npm ci --silent

# start app
CMD ["npm", "start"]