FROM node:10.11.0-alpine as builder

# Set working directory
RUN mkdir /usr/src
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# Add /usr/src/app/node_modules/.bin to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Get build arguments coming from .env file
ARG API_URL
ENV API_URL "$API_URL"

# Create config file to from environment variables
RUN echo "API_URL = $API_URL" > ./app.cfg
# ENTRYPOINT echo "API_URL = $API_URL" > ./app.cfg # Attempt to overwrite variable at run time but does not work

# Install and cache app dependencies
RUN npm i -g --silent react-scripts@2.0.3
COPY package.json package-lock.json /usr/src/app/
RUN npm ci --silent
COPY . /usr/src/app
RUN npm run build

# Production environment
FROM nginx:1.15.4-alpine
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
